# Generated by Django 4.1.7 on 2023-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_application_id_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
