# Generated by Django 4.1.7 on 2023-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
