# Generated by Django 4.2 on 2023-04-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_avtotest_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtotest',
            options={'ordering': ['raqam']},
        ),
        migrations.AlterModelManagers(
            name='avtotest',
            managers=[
            ],
        ),
    ]
