# Generated by Django 4.2 on 2023-05-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_books_alter_topics_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['id'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='answers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='books',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='books',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='updated_by',
        ),
    ]
