# Generated by Django 4.2 on 2023-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_answers_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/tests/answers/images'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/tests/questions/images'),
        ),
    ]
