# Generated by Django 4.2 on 2023-12-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_answers_image_alter_questions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='group',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='book',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
