# Generated by Django 4.2 on 2023-11-15 11:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en_us', models.CharField(max_length=255)),
                ('title_ru_ru', models.CharField(max_length=255)),
                ('title_uz_crl', models.CharField(max_length=255)),
                ('title_uz_uz', models.CharField(max_length=255)),
                ('body_en_us', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_ru_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_uz_crl', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_uz_uz', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(blank=True, upload_to='news/<django.db.models.fields.UUIDField>/images')),
                ('sort_number', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
