# Generated by Django 4.2 on 2023-12-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['sort_number'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name_en_us',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name_ru_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name_uz_crl',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name_uz_uz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_en_us',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_ru_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_uz_crl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title_uz_uz',
            field=models.TextField(),
        ),
    ]
