# Generated by Django 4.2 on 2024-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_posts_options_alter_posts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='sort_number',
            field=models.IntegerField(default=0),
        ),
    ]
