# Generated by Django 4.2 on 2024-02-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='view_count',
        ),
    ]
