# Generated by Django 4.2 on 2024-09-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
