# Generated by Django 4.2 on 2024-09-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_image_code_remove_image_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='type',
            name='created_by',
        ),
    ]
