"""
Django settings for django_complexprogrammer project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# if request.device.is_mobile:
# ALLOWED_HOSTS =  ['*']
ALLOWED_HOSTS =  ['complexprogrammer.uz', 'www.complexprogrammer.uz', 'complexprogrammer-dev.uz', 'www.complexprogrammer-dev.uz', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'projects',
    'whitenoise.runserver_nostatic',
    'django_extensions',
    'mobiledetect',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'mobiledetect.middleware.DetectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_complexprogrammer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'django_complexprogrammer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

USE_L10N = True

LANGUAGES = (
    ('uz', _('Uzbek')),
    ('en', _('English')),
    ('tr', _('Turkish')),
    ('ru', _('Russia')),
)

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL='/media/'
STATICFILES_DIRS=[BASE_DIR / 'static', BASE_DIR / 'media']
STATIC_ROOT=BASE_DIR / 'staticfiles'
MEDIA_ROOT=BASE_DIR / 'media'
# if DEBUG == True:
#     STATICFILES_DIRS=[BASE_DIR / 'static', BASE_DIR / 'media']
#     STATIC_ROOT=BASE_DIR / 'staticfiles'
#     MEDIA_ROOT=BASE_DIR / 'media'
# else:
#     STATICFILES_DIRS = (
#                         '/home/complex1/complexprogrammer.uz/django/static',
#                         '/home/complex1/complexprogrammer.uz/django/media',
#                    )
#     STATIC_ROOT = '/home/complex1/complexprogrammer.uz/django/staticfiles'
#     MEDIA_ROOT='/home/complex1/complexprogrammer.uz/django/media'



STATICFILES_FINDERS=[
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# APPEND_SLASH=False
GET_FILE_FORMATS = {'.mp3', '.mp4', '.zip', '.xml'}
UPLOAD_FOLDER_VIDEOS = STATIC_URL+'uploaded_videos/'
CARTOONIZED_FOLDER = STATIC_URL+'cartoonized_images/'
WRITE_BOX_CARTOONIZER = STATIC_URL+'white_box_cartoonizer/'


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
if DEBUG:
    SECURE_SSL_REDIRECT = False
else:
    SECURE_SSL_REDIRECT = True