# Generated by Django 5.1.1 on 2025-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_remove_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
