# Generated by Django 4.2 on 2024-08-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='markets/stores/products/images'),
        ),
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.category'),
            preserve_default=False,
        ),
    ]
