# Generated by Django 4.2 on 2024-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_category_parent_market_parent_store_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='markets/categories/images'),
        ),
        migrations.AddField(
            model_name='market',
            name='logo',
            field=models.ImageField(blank=True, upload_to='markets/logos'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, upload_to='markets/stores/logos'),
        ),
    ]
