# Generated by Django 4.2 on 2023-11-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('book_type', models.CharField(choices=[('none', 'None'), ('avto_test_uzb', 'Avto Test Uzb'), ('avto_test_usa', 'Avto Test Usa')], default='none', max_length=20)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tests.books')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='projects/tests/questions/images')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.topics')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='tests.groups'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name_en_us', models.TextField()),
                ('name_ru_ru', models.TextField()),
                ('name_uz_crl', models.TextField()),
                ('name_uz_uz', models.TextField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='projects/tests/answers/images')),
                ('right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.questions')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['number'],
            },
        ),
    ]
