# Generated by Django 4.2 on 2023-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_books_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_type',
            field=models.CharField(choices=[('usa_avto_test', 'None')], default='usa_avto_test', max_length=20),
        ),
    ]
