# Generated by Django 4.2 on 2023-12-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_groups_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
