# Generated by Django 4.2 on 2023-12-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_booktypes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_type',
        ),
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='tests.booktypes'),
        ),
    ]
