# Generated by Django 4.2 on 2023-12-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_remove_books_book_type_books_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='image',
            field=models.ImageField(blank=True, upload_to='tests/answers/images'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, upload_to='tests/questions/images'),
        ),
    ]
