# Generated by Django 4.2 on 2024-01-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_groups_image_topics_image_types_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name_ru_ru',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name_uz_crl',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name_uz_uz',
        ),
        migrations.AddField(
            model_name='answers',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='tests.books'),
        ),
        migrations.AddField(
            model_name='answers',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='tests.groups'),
        ),
        migrations.AddField(
            model_name='answers',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='tests.topics'),
        ),
        migrations.AddField(
            model_name='answers',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='tests.types'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='tests.booktypes'),
        ),
        migrations.AddField(
            model_name='booktypes',
            name='name_en_us',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktypes',
            name='name_ru_ru',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktypes',
            name='name_uz_crl',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktypes',
            name='name_uz_uz',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='tests.books'),
        ),
        migrations.AddField(
            model_name='questions',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='tests.groups'),
        ),
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='tests.types'),
        ),
        migrations.AddField(
            model_name='topics',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to='tests.groups'),
        ),
        migrations.AddField(
            model_name='topics',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to='tests.types'),
        ),
        migrations.AlterField(
            model_name='books',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='tests.types'),
        ),
    ]
