# Generated by Django 5.1.1 on 2025-08-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchiveStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Holati"
                    ),
                ),
            ],
            options={
                "verbose_name": "Holat",
                "verbose_name_plural": "Holatlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Turi"),
                ),
            ],
            options={
                "verbose_name": "Arxiv turi",
                "verbose_name_plural": "Arxiv turlari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Shkaf raqami"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shkaf",
                "verbose_name_plural": "Shkaflar",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Xona raqami"
                    ),
                ),
            ],
            options={
                "verbose_name": "Xona",
                "verbose_name_plural": "Xonalar",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cabinet_floor",
                    models.CharField(max_length=50, verbose_name="Shkaf qavati"),
                ),
                (
                    "register_number",
                    models.CharField(max_length=100, verbose_name="Reyestr raqami"),
                ),
                (
                    "request_number",
                    models.CharField(max_length=100, verbose_name="Talabnoma raqami"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="arxiv/documents/",
                        verbose_name="Hujjat",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_items",
                        to="arxiv.archivestatus",
                        verbose_name="Holati",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_items",
                        to="arxiv.archivetype",
                        verbose_name="Turi",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_items",
                        to="arxiv.cabinet",
                        verbose_name="Shkaf",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_items",
                        to="arxiv.room",
                        verbose_name="Xona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arxiv yozuvi",
                "verbose_name_plural": "Arxiv yozuvlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
