# Generated by Django 5.1.1 on 2025-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arxiv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveitem",
            name="patent_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Patent raqami"
            ),
        ),
    ]
