# Generated by Django 5.1.1 on 2025-08-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arxiv", "0002_archiveitem_patent_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveitem",
            name="is_public",
            field=models.BooleanField(
                default=True, verbose_name="Foydalanuvchilar ko'ra oladi"
            ),
        ),
    ]
